version: "3.8"
services:
    unesco_app:
        build:
            context: .
            dockerfile: Dockerfile
        image: unesco-app
        container_name: unesco_app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./vendor:/var/www/vendor
            - ./node_modules:/var/www/node_modules
        networks:
            - laravel

    unesco_webserver:
        image: nginx:alpine
        container_name: nginx_server
        restart: unless-stopped
        tty: true
        ports:
            - "8040:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
